using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace WinGamma
{
    public static class IccProfile
    {
        private const string VcgtSignature = "vcgt";
        private const string MetadataSignature = "wGma";

        private sealed class TagRecord
        {
            public string Signature;
            public byte[] Data;
        }

        public static bool IsValid(byte[] bytes)
        {
            if (bytes == null || bytes.Length < 132)
                return false;
            if (ReadAscii(bytes, 36, 4) != "acsp")
                return false;
            uint declaredSize = ReadUInt32(bytes, 0);
            if (declaredSize < 132 || declaredSize > bytes.Length)
                return false;
            try
            {
                ReadTags(bytes);
                return true;
            }
            catch
            {
                return false;
            }
        }

        public static GammaRamp ReadVcgt(byte[] bytes)
        {
            if (!IsValid(bytes))
                return null;

            List<TagRecord> tags = ReadTags(bytes);
            for (int i = 0; i < tags.Count; i++)
            {
                if (tags[i].Signature == VcgtSignature)
                    return ParseVcgt(tags[i].Data);
            }
            return null;
        }

        public static WinGammaMetadata ReadMetadata(byte[] bytes)
        {
            if (!IsValid(bytes))
                return null;

            List<TagRecord> tags = ReadTags(bytes);
            for (int i = 0; i < tags.Count; i++)
            {
                if (tags[i].Signature != MetadataSignature)
                    continue;
                byte[] data = tags[i].Data;
                if (data.Length < 9)
                    return null;
                string type = ReadAscii(data, 0, 4);
                int payloadOffset;
                if (type == "data" && data.Length >= 13)
                    payloadOffset = 12;
                else if (type == "text")
                    payloadOffset = 8;
                else
                    return null;
                int length = data.Length - payloadOffset;
                if (length > 0 && data[data.Length - 1] == 0)
                    length--;
                string payload = Encoding.UTF8.GetString(data, payloadOffset, length);
                return ParseMetadata(payload);
            }
            return null;
        }

        public static byte[] CreateProfile(byte[] baseProfile, GammaRamp ramp,
            WinGammaMetadata metadata)
        {
            if (!IsValid(baseProfile))
                throw new InvalidDataException("The base ICC profile is invalid.");
            if (ramp == null || !GammaMath.IsMonotonic(ramp))
                throw new InvalidDataException("The gamma ramp is invalid.");

            byte[] header = new byte[128];
            Array.Copy(baseProfile, header, 128);
            List<TagRecord> source = ReadTags(baseProfile);
            List<TagRecord> output = new List<TagRecord>();
            bool vcgtWritten = false;
            bool metadataWritten = false;

            for (int i = 0; i < source.Count; i++)
            {
                TagRecord tag = source[i];
                if (tag.Signature == VcgtSignature)
                {
                    if (!vcgtWritten)
                    {
                        output.Add(NewTag(VcgtSignature, CreateVcgt(ramp)));
                        vcgtWritten = true;
                    }
                }
                else if (tag.Signature == MetadataSignature)
                {
                    if (!metadataWritten)
                    {
                        output.Add(NewTag(MetadataSignature, CreateMetadataTag(metadata)));
                        metadataWritten = true;
                    }
                }
                else
                {
                    output.Add(tag);
                }
            }

            if (!vcgtWritten)
                output.Add(NewTag(VcgtSignature, CreateVcgt(ramp)));
            if (!metadataWritten)
                output.Add(NewTag(MetadataSignature, CreateMetadataTag(metadata)));

            return Build(header, output);
        }

        public static byte[] CreateGenericSrgbProfile()
        {
            byte[] header = CreateSrgbHeader();
            List<TagRecord> tags = new List<TagRecord>();
            tags.Add(NewTag("desc", CreateDescription("WinGamma sRGB base")));
            tags.Add(NewTag("cprt", CreateText("Generated by WinGamma")));
            tags.Add(NewTag("wtpt", CreateXyz(0.9642, 1.0, 0.8249)));
            tags.Add(NewTag("rXYZ", CreateXyz(0.4360747, 0.2225045, 0.0139322)));
            tags.Add(NewTag("gXYZ", CreateXyz(0.3850649, 0.7168786, 0.0971045)));
            tags.Add(NewTag("bXYZ", CreateXyz(0.1430804, 0.0606169, 0.7141733)));
            tags.Add(NewTag("rTRC", CreateCurve(2.2)));
            tags.Add(NewTag("gTRC", CreateCurve(2.2)));
            tags.Add(NewTag("bTRC", CreateCurve(2.2)));
            tags.Add(NewTag(VcgtSignature, CreateVcgt(GammaMath.Identity())));
            return Build(header, tags);
        }

        private static GammaRamp ParseVcgt(byte[] data)
        {
            if (data == null || data.Length < 18 || ReadAscii(data, 0, 4) != "vcgt")
                return null;
            uint gammaType = ReadUInt32(data, 8);
            if (gammaType != 0)
                return null;
            int channels = ReadUInt16(data, 12);
            int entries = ReadUInt16(data, 14);
            int entrySize = ReadUInt16(data, 16);
            if (channels != 3 || entries < 2 || (entrySize != 1 && entrySize != 2))
                return null;

            long required = 18L + ((long)channels * entries * entrySize);
            if (required > data.Length)
                return null;

            ushort[][] source = new ushort[3][];
            int position = 18;
            for (int channel = 0; channel < 3; channel++)
            {
                source[channel] = new ushort[entries];
                for (int entry = 0; entry < entries; entry++)
                {
                    source[channel][entry] = entrySize == 1
                        ? (ushort)(data[position++] * 257)
                        : ReadUInt16AndAdvance(data, ref position);
                }
            }

            GammaRamp ramp = new GammaRamp();
            Resample(source[0], ramp.Red);
            Resample(source[1], ramp.Green);
            Resample(source[2], ramp.Blue);
            return ramp;
        }

        private static byte[] CreateVcgt(GammaRamp ramp)
        {
            byte[] data = new byte[18 + (3 * 256 * 2)];
            WriteAscii(data, 0, "vcgt");
            WriteUInt32(data, 8, 0);
            WriteUInt16(data, 12, 3);
            WriteUInt16(data, 14, 256);
            WriteUInt16(data, 16, 2);
            int position = 18;
            WriteRampChannel(data, ref position, ramp.Red);
            WriteRampChannel(data, ref position, ramp.Green);
            WriteRampChannel(data, ref position, ramp.Blue);
            return data;
        }

        private static byte[] CreateMetadataTag(WinGammaMetadata metadata)
        {
            string payload = SerializeMetadata(metadata);
            byte[] text = Encoding.UTF8.GetBytes(payload);
            byte[] data = new byte[12 + text.Length + 1];
            WriteAscii(data, 0, "data");
            WriteUInt32(data, 8, 1);
            Array.Copy(text, 0, data, 12, text.Length);
            return data;
        }

        private static string SerializeMetadata(WinGammaMetadata metadata)
        {
            if (metadata == null)
                metadata = new WinGammaMetadata();
            if (metadata.Settings == null)
                metadata.Settings = new GammaSettings();

            GammaSettings s = metadata.Settings;
            string path = metadata.BaseProfilePath ?? String.Empty;
            string encodedPath = Convert.ToBase64String(Encoding.UTF8.GetBytes(path));
            return String.Join(";", new[]
            {
                "v=" + Math.Max(1, metadata.Version).ToString(CultureInfo.InvariantCulture),
                "base64=" + encodedPath,
                "gr=" + s.GammaRed.ToString("R", CultureInfo.InvariantCulture),
                "gg=" + s.GammaGreen.ToString("R", CultureInfo.InvariantCulture),
                "gb=" + s.GammaBlue.ToString("R", CultureInfo.InvariantCulture),
                "br=" + s.Brightness.ToString("R", CultureInfo.InvariantCulture),
                "co=" + s.Contrast.ToString("R", CultureInfo.InvariantCulture),
                "tk=" + s.Temperature.ToString(CultureInfo.InvariantCulture),
                "tg=" + s.TargetGamma.ToString("R", CultureInfo.InvariantCulture),
                "ln=" + (s.LinkChannels ? "1" : "0")
            });
        }

        private static WinGammaMetadata ParseMetadata(string payload)
        {
            try
            {
                Dictionary<string, string> values =
                    new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                string[] items = payload.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
                for (int i = 0; i < items.Length; i++)
                {
                    int separator = items[i].IndexOf('=');
                    if (separator > 0)
                        values[items[i].Substring(0, separator)] = items[i].Substring(separator + 1);
                }

                WinGammaMetadata result = new WinGammaMetadata();
                result.Version = ParseInt(values, "v", 1);
                string encoded;
                if (values.TryGetValue("base64", out encoded))
                    result.BaseProfilePath = Encoding.UTF8.GetString(Convert.FromBase64String(encoded));
                result.Settings = new GammaSettings();
                result.Settings.GammaRed = ParseDouble(values, "gr", 1.0);
                result.Settings.GammaGreen = ParseDouble(values, "gg", 1.0);
                result.Settings.GammaBlue = ParseDouble(values, "gb", 1.0);
                result.Settings.Brightness = ParseDouble(values, "br", 0.0);
                result.Settings.Contrast = ParseDouble(values, "co", 1.0);
                result.Settings.Temperature = ParseInt(values, "tk", 6500);
                result.Settings.TargetGamma = ParseDouble(values, "tg", 2.2);
                string linked;
                result.Settings.LinkChannels =
                    !values.TryGetValue("ln", out linked) || linked == "1";
                return result;
            }
            catch
            {
                return null;
            }
        }

        private static List<TagRecord> ReadTags(byte[] bytes)
        {
            uint count = ReadUInt32(bytes, 128);
            if (count > 4096 || 132L + (count * 12L) > bytes.Length)
                throw new InvalidDataException("Invalid ICC tag table.");

            List<TagRecord> tags = new List<TagRecord>();
            for (uint i = 0; i < count; i++)
            {
                int entry = 132 + (int)(i * 12);
                string signature = ReadAscii(bytes, entry, 4);
                uint offset = ReadUInt32(bytes, entry + 4);
                uint size = ReadUInt32(bytes, entry + 8);
                if (size > Int32.MaxValue || offset > bytes.Length
                    || (long)offset + size > bytes.Length)
                    throw new InvalidDataException("Invalid ICC tag bounds.");
                byte[] data = new byte[(int)size];
                Array.Copy(bytes, (int)offset, data, 0, (int)size);
                tags.Add(NewTag(signature, data));
            }
            return tags;
        }

        private static byte[] Build(byte[] sourceHeader, List<TagRecord> tags)
        {
            int tableSize = 4 + (tags.Count * 12);
            int dataOffset = Align4(128 + tableSize);
            int totalSize = dataOffset;
            for (int i = 0; i < tags.Count; i++)
                totalSize += Align4(tags[i].Data.Length);

            byte[] output = new byte[totalSize];
            Array.Copy(sourceHeader, output, Math.Min(128, sourceHeader.Length));
            WriteUInt32(output, 0, (uint)totalSize);
            WriteUInt32(output, 128, (uint)tags.Count);

            int current = dataOffset;
            for (int i = 0; i < tags.Count; i++)
            {
                int entry = 132 + (i * 12);
                WriteAscii(output, entry, tags[i].Signature);
                WriteUInt32(output, entry + 4, (uint)current);
                WriteUInt32(output, entry + 8, (uint)tags[i].Data.Length);
                Array.Copy(tags[i].Data, 0, output, current, tags[i].Data.Length);
                current += Align4(tags[i].Data.Length);
            }

            UpdateProfileId(output);
            return output;
        }

        private static void UpdateProfileId(byte[] profile)
        {
            byte[] hashInput = (byte[])profile.Clone();
            Array.Clear(hashInput, 44, 4);
            Array.Clear(hashInput, 64, 4);
            Array.Clear(hashInput, 84, 16);
            using (MD5 md5 = MD5.Create())
            {
                byte[] digest = md5.ComputeHash(hashInput);
                Array.Copy(digest, 0, profile, 84, 16);
            }
        }

        private static byte[] CreateSrgbHeader()
        {
            byte[] header = new byte[128];
            WriteAscii(header, 4, "wGma");
            WriteUInt32(header, 8, 0x02100000);
            WriteAscii(header, 12, "mntr");
            WriteAscii(header, 16, "RGB ");
            WriteAscii(header, 20, "XYZ ");
            DateTime now = DateTime.UtcNow;
            WriteUInt16(header, 24, (ushort)now.Year);
            WriteUInt16(header, 26, (ushort)now.Month);
            WriteUInt16(header, 28, (ushort)now.Day);
            WriteUInt16(header, 30, (ushort)now.Hour);
            WriteUInt16(header, 32, (ushort)now.Minute);
            WriteUInt16(header, 34, (ushort)now.Second);
            WriteAscii(header, 36, "acsp");
            WriteAscii(header, 40, "MSFT");
            WriteFixed(header, 68, 0.9642);
            WriteFixed(header, 72, 1.0);
            WriteFixed(header, 76, 0.8249);
            WriteAscii(header, 80, "wGma");
            return header;
        }

        private static byte[] CreateDescription(string value)
        {
            byte[] ascii = Encoding.ASCII.GetBytes(value);
            byte[] data = new byte[12 + ascii.Length + 1 + 4 + 4 + 2 + 1 + 67];
            WriteAscii(data, 0, "desc");
            WriteUInt32(data, 8, (uint)(ascii.Length + 1));
            Array.Copy(ascii, 0, data, 12, ascii.Length);
            int position = 12 + ascii.Length + 1;
            WriteUInt32(data, position, 0);
            WriteUInt32(data, position + 4, 0);
            return data;
        }

        private static byte[] CreateText(string value)
        {
            byte[] ascii = Encoding.ASCII.GetBytes(value);
            byte[] data = new byte[8 + ascii.Length + 1];
            WriteAscii(data, 0, "text");
            Array.Copy(ascii, 0, data, 8, ascii.Length);
            return data;
        }

        private static byte[] CreateXyz(double x, double y, double z)
        {
            byte[] data = new byte[20];
            WriteAscii(data, 0, "XYZ ");
            WriteFixed(data, 8, x);
            WriteFixed(data, 12, y);
            WriteFixed(data, 16, z);
            return data;
        }

        private static byte[] CreateCurve(double gamma)
        {
            byte[] data = new byte[14];
            WriteAscii(data, 0, "curv");
            WriteUInt32(data, 8, 1);
            WriteUInt16(data, 12, (ushort)Math.Round(gamma * 256.0));
            return data;
        }

        private static TagRecord NewTag(string signature, byte[] data)
        {
            TagRecord tag = new TagRecord();
            tag.Signature = signature;
            tag.Data = data;
            return tag;
        }

        private static void Resample(ushort[] source, ushort[] destination)
        {
            for (int i = 0; i < destination.Length; i++)
            {
                double position = i / 255.0 * (source.Length - 1);
                int lower = (int)Math.Floor(position);
                int upper = Math.Min(source.Length - 1, lower + 1);
                double fraction = position - lower;
                destination[i] = (ushort)Math.Round(source[lower]
                    + ((source[upper] - source[lower]) * fraction));
            }
        }

        private static void WriteRampChannel(byte[] data, ref int position, ushort[] values)
        {
            for (int i = 0; i < values.Length; i++)
            {
                WriteUInt16(data, position, values[i]);
                position += 2;
            }
        }

        private static ushort ReadUInt16AndAdvance(byte[] bytes, ref int position)
        {
            ushort value = ReadUInt16(bytes, position);
            position += 2;
            return value;
        }

        private static string ReadAscii(byte[] bytes, int offset, int count)
        {
            if (offset < 0 || count < 0 || offset + count > bytes.Length)
                throw new InvalidDataException("Unexpected end of ICC data.");
            return Encoding.ASCII.GetString(bytes, offset, count);
        }

        private static void WriteAscii(byte[] bytes, int offset, string value)
        {
            byte[] data = Encoding.ASCII.GetBytes(value);
            if (data.Length != 4)
                throw new ArgumentException("ICC signatures must contain four ASCII characters.");
            Array.Copy(data, 0, bytes, offset, 4);
        }

        private static ushort ReadUInt16(byte[] bytes, int offset)
        {
            return (ushort)((bytes[offset] << 8) | bytes[offset + 1]);
        }

        private static uint ReadUInt32(byte[] bytes, int offset)
        {
            return ((uint)bytes[offset] << 24)
                | ((uint)bytes[offset + 1] << 16)
                | ((uint)bytes[offset + 2] << 8)
                | bytes[offset + 3];
        }

        private static void WriteUInt16(byte[] bytes, int offset, ushort value)
        {
            bytes[offset] = (byte)(value >> 8);
            bytes[offset + 1] = (byte)value;
        }

        private static void WriteUInt32(byte[] bytes, int offset, uint value)
        {
            bytes[offset] = (byte)(value >> 24);
            bytes[offset + 1] = (byte)(value >> 16);
            bytes[offset + 2] = (byte)(value >> 8);
            bytes[offset + 3] = (byte)value;
        }

        private static void WriteFixed(byte[] bytes, int offset, double value)
        {
            int fixedValue = (int)Math.Round(value * 65536.0);
            WriteUInt32(bytes, offset, unchecked((uint)fixedValue));
        }

        private static int Align4(int value)
        {
            return (value + 3) & ~3;
        }

        private static int ParseInt(Dictionary<string, string> values, string key, int fallback)
        {
            string text;
            int result;
            return values.TryGetValue(key, out text)
                && Int32.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out result)
                ? result : fallback;
        }

        private static double ParseDouble(Dictionary<string, string> values, string key,
            double fallback)
        {
            string text;
            double result;
            return values.TryGetValue(key, out text)
                && Double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out result)
                ? result : fallback;
        }
    }
}
